plugins: rubocop-rubycw

inherit_mode:
  merge:
    - Exclude

AllCops:
  DisabledByDefault: true
  Exclude:
    - 'mruby/**/*'
  NewCops: enable
Bundler:
  Enabled: true
Gemspec:
  Enabled: true
Layout:
  Enabled: true
Lint:
  Enabled: true
Lint/SymbolConversion:
  Enabled: false
Rubycw/Rubycw:
  Enabled: true
Security:
  Enabled: true
