name: CI
on:
  push:

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 5
          submodules: true

      - name: make
        run: make

      - name: smoke
        run: make smoke
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

  unit:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true

      - name: make
        run: make

      - name: test
        run: make test
