name: Release CLI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04-arm, macos-14]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true

      - name: Build CLI
        run: make

      - name: Rename binary
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-24.04-arm" ]]; then
            mv mi mi-linux-arm64
          else
            mv mi mi-macos-arm64
          fi

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        with:
          files: |
            mi-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
